Repository 24avepizza/qrgen, pull requests merged in 2020-10, with the labels that each got.

#9 Added some basic frames
  qrgen/main.py
Labels: enhancement, hacktoberfest-accepted, help wanted

#10 Deleted some unwanted classes
  qrgen/main.py
Labels: enhancement, hacktoberfest-accepted

#11 Update main.py
  qrgen/main.py
Labels: enhancement, hacktoberfest-accepted

#12 Added file upload
  qrgen/main.py
Labels: enhancement, hacktoberfest-accepted

#13 enchanced the qrcode function
  .gitignore
  qrgen/main.py
Labels: enhancement, hacktoberfest-accepted

#14 Completed the GUI with some enhancements
  qrgen/main.py
Labels: enhancement, hacktoberfest-accepted

#17 Update CONTRIBUTING.RST
  CONTRIBUTING.RST
Labels: documentation, hacktoberfest-accepted
